version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:  ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  python-script:
    build: ./python-script
    environment:
      MONGODB_URI: mongodb://countly:HnBc9pM33R@34.79.61.151:27017/?authMechanism=DEFAULT&authSource=admin
      MONGODB_DB: countly
      POSTGRES_DB: countly
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    depends_on:
      - postgres

volumes:
  postgres_data:
